### ISSUE TITLE
Include tests on pypi release

### ISSUE THREAD

**Issue by Jenselme** [methane/wsaccel#11]
Hi,

Can you please include the test files in the pypi release?

Can you also help me to launch the tests? I launched in the root folder against mater `python -m unittest discover -s tests` (which is not able to find utf8validator and  xormask) and `PYTHONPATH=build/lib.linux-x86_64-2.7 python -m unittest discover -s tests` which doesn't find any tests.

**Comment by methane** [comment]
I usually use pytest for personal projects.
```console
$ pip install pytest
$ py.test tests
```

**Comment by Jenselme** [comment]
> I usually use pytest for personal projects.

So do I. And yet, I didn't think to try it :-(
