### ISSUE TITLE
deprecated buffer protocol API

### ISSUE THREAD

**Issue by hrnciar** [methane/wsaccel#22]
python-wsaccel fails to build with Python 3.10.0a2.

==================================== ERRORS ====================================
_______________________ ERROR collecting tests/test_4.py _______________________
ImportError while importing test module '/builddir/build/BUILD/wsaccel-0.6.2/tests/test_4.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_4.py:2: in <module>
    import wsaccel.utf8validator
E   ImportError: /builddir/build/BUILD/wsaccel-0.6.2/build/lib.linux-x86_64-3.10/wsaccel/utf8validator.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_AsReadBuffer
____________________ ERROR collecting tests/test_xormask.py ____________________
ImportError while importing test module '/builddir/build/BUILD/wsaccel-0.6.2/tests/test_xormask.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_xormask.py:1: in <module>
    from wsaccel.xormask import XorMaskerSimple
E   ImportError: /builddir/build/BUILD/wsaccel-0.6.2/build/lib.linux-x86_64-3.10/wsaccel/xormask.cpython-310-x86_64-linux-gnu.so: undefined symbol: PyObject_AsReadBuffer
=========================== short test summary info ============================
ERROR tests/test_4.py
ERROR tests/test_xormask.py
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 2 errors in 0.07s ===============================

https://docs.python.org/3.10/whatsnew/changelog.html#id16

bpo-41103: PyObject_AsCharBuffer(), PyObject_AsReadBuffer(), PyObject_CheckReadBuffer(), and PyObject_AsWriteBuffer() are removed. Please migrate to new buffer protocol; PyObject_GetBuffer() and PyBuffer_Release().

**Comment by methane** [comment]
I think b171314d883df04bf5449085e017e44dee21231f will fix it.
But I don't have Travis-CI credits...
