### ISSUE TITLE
Masking round-trip

### ISSUE THREAD

**Issue by dsuch** [methane/wsaccel#24]
Hello,

I am using wsaccel 0.6.3 installed from PyPI under Python 3.6.8.

Please consider the code below, noting that the data is 1 byte longer than the masking key.

I am not sure if I understand it correctly, should not the masking process round-trip to return the same input data as it was given initially in this example?

Or should the input be a multiple of the masking key's length and wsaccel assumes that a given WebSocket library will ensure it?

Thank you.

```python
# -*- coding: utf-8 -*-

# wsaccel
from wsaccel.xormask import XorMaskerSimple

# Test data - note that it is 5 bytes
data = b'aaaaa'

# Masking key to use - 4 bytes
masking_key = b'\x80@\x06\xce'

# Create a new maker
masker = XorMaskerSimple(masking_key)

# Now, mask input data ..
masked = masker.process(data)

# .. unmask it ..
unmasked = masker.process(masked)

# .. and report the result.
print('Data', data)
print('Masked', masked)
print('Unmasked', unmasked)
```

Result:

```
Data b'aaaaa'
Masked b'\xe1!g\xaf\xe1'
Unmasked b"\xa1'\xa9/\xa1"
```

**Comment by dsuch** [comment]
For comparison, I have checked ws4py and below are the results.

If what ws4py produces is different than what wsaccel is doing then I am not sure how to understand what patch_ws4py is doing because it, essentially, replaces **ws4py.framing.Frame:mask** with **XorMaskerSimple:process**?

```python
# -*- coding: utf-8 -*-

# ws4py
from ws4py.framing import Frame

# Test data - note that it is 5 bytes
data = b'aaaaa'

# Masking key to use - 4 bytes
masking_key = b'\x80@\x06\xce'

frame = Frame(masking_key=masking_key)
masked = frame.mask(data)
unmasked = frame.mask(masked)

print('Data #2', data)
print('Masked #2', masked)
print('Unmasked #2', unmasked)
```

```
Data #2 b'aaaaa'
Masked #2 bytearray(b'\xe1!g\xaf\xe1')
Unmasked #2 bytearray(b'aaaaa')
```

**Comment by methane** [comment]
You need to create a new masker instance every time.

Note that XorMaskerSimple is drop-in replacement of XorMaskerSimple in autobahn-python.
https://github.com/crossbario/autobahn-python/blob/3ea4fdae9814641f6dcc03a2deb4e555b2f9a776/autobahn/websocket/xormasker.py#L69

**Comment by dsuch** [comment]
Thanks, essentially - a new masker for each frame in the context of WebSockets?
